### PR TITLE
M12 & M13 lab errors

### PR DESCRIPTION
**Pull request by ashutosh1919**
Professor @yy, I have resolved errors in `m12` and `m13` lab notebooks and below were the erros.

### M12:
- Failing because the data frame was not defined and data was not fetched from Kaggle. I have handled the error and created the dummy data frame along with the instruction that this dummy data is not for assignment purposes.

### M13:
- GitHub workflow didn't have `en_core_web_sm` installed. So, I added a command to install that.
- `metamorphosis_book` is a byte but `nlp()` object expects `str` and that is why it was failing. I handled the error and printed the same.

Hurray! 🎉😁 With this, All errors resolved in all the notebooks, and our workflow is succeeded in this PR.

### CODE REVIEW

**Comment by yy** [comment]
Awesome! Just one thing. The metamorphosis book error was intentional, to explain why it's failing. (str vs. bytes) So I'd add a comment to instruct to run the command and think about why it's failing.

**Comment by ashutosh1919** [comment]
Professor @yy, Yes I know it was intentional and I have not removed it. It is as it is but I just handled it in workflow so that it won't give an error. Instead, it would give an exception.

**Comment by yy** [comment]
Yeah I understand. I'm suggesting to add some comments, say

```python
# Try to run this command `xxxxx`. Why doesn't it work? Think about it for a moment before moving on!
```

or something along this line..

**Comment by ashutosh1919** [comment]
Professor @yy, I have added the comment as you suggested.

**Pull request merged**
