### PR TITLE
lab 08, adding a hint

### PR DESCRIPTION
**Pull request by jaehyukpark**

### CODE REVIEW

**Comment by yy** [comment]
what's the change in the m07 lab?

**Comment by jaehyukpark** [comment]
> what's the change in the m07 lab?

Oh it's about python version on the screen (prev: 3.6, mine:3.7)

**Comment by yy** [comment]
But there seem to be many more images in the notebook (based on the diff; right now GitHub doesn’t render the notebook)

**Comment by jaehyukpark** [comment]
I think I never opened the lab07 file yet, but I'll check. Actually, now I just begin to figure out the error in lab07 that multiple students reported, so I'll add to this pull request after checking the error.

**Comment by jaehyukpark** [comment]
I fixed the two errors in lab07: 1) the given histogram was wrong (the one with density=True) although looks similar, which made students confused because they couldn't make the exact same figure, 2) In the stripplot(), the default seems "jitter=True", so I added "jitter=False" to the first code.

I'm checking the some "image=..." lines that are reported as added but don't know what it means... I didn't add any more figures to existing ones, so just guess those are just some ipython records added in jupyter lab (I'm using jupyter lab, not juypter notebook for checking).

**Pull request merged**
