### PR TITLE
m07 lab minor jitter flag update

### PR DESCRIPTION
**Pull request by johnyrufus**
The diff does not show the exact change, as the ipynb file changes a lot when loaded and executed. The exact changes are

1. "And you can easily add jitters or even create a beeswarm plot."
to
"And you can easily add jitters (which is the default behavior in newer versions) or even create a beeswarm plot."

2. "sns.stripplot(x='Origin', y='Acceleration', data=cars)"
to 
"sns.stripplot(x='Origin', y='Acceleration', data=cars, jitter=False)"

3. The chart as a result of the execution of the above code.

### CODE REVIEW

**Comment by yzjing** [comment]
Will take care of this tomorrow 

Elise

**Comment by johnyrufus** [comment]
Thanks Elise for the review. I can go ahead and make the changes.
One quick question, showing both the jittered and non jittered versions, like in the original notebook, gives a good idea as to how the jitter adds a difference to the viz. Do we want to delete that cell ? (Just double checking :) )

**Comment by yzjing** [comment]
That’s a good call! I think people would already have an idea of how jittering versus non-jittering look like from the previous plots so it should be ok.

Elise

**Comment by johnyrufus** [comment]
> That’s a good call! I think people would already have an idea of how jittering versus non-jittering look like from the previous plots so it should be ok. Elise

Thanks for the comment. Done.

**Pull request merged**
